# Generated by Django 5.0 on 2024-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_confusionmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_class_0', models.FloatField(blank=True, null=True)),
                ('recall_class_0', models.FloatField(blank=True, null=True)),
                ('f1_class_0', models.FloatField(blank=True, null=True)),
                ('precision_class_1', models.FloatField(blank=True, null=True)),
                ('recall_class_1', models.FloatField(blank=True, null=True)),
                ('f1_class_1', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
